// 错误类型定义
const NAME_OR_PASSWORD_IS_REQUIRED = '用户名或密码不能为空~';
const USERNAME_ALEADY_EXISTS = '用户名已存在';
const USER_DOES_NOT_EXISTS = '用户不存在';
const INCORRECT_USERNAME_OR_PASSWORD = '用户名或密码错误';
const UNAUTHORIZED = '未授权的，无效的Token~';
const UNPREMISSION = '您不具备此操作的权限~';
const MISSING_REQUIRED_PARAMETERS = '缺少必要参数';

module.exports = {
  NAME_OR_PASSWORD_IS_REQUIRED,
  USERNAME_ALEADY_EXISTS,
  USER_DOES_NOT_EXISTS,
  INCORRECT_USERNAME_OR_PASSWORD,
  UNAUTHORIZED,
  UNPREMISSION,
  MISSING_REQUIRED_PARAMETERS
}